version: '3.1'

services:
  db:
    image: mariadb:10.6
    volumes:
      - db:/var/lib/mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
      MYSQL_DATABASE: saasapp
  site:
    depends_on:
      - db
    volumes:
      - ./html/public:/var/www/html
      - ./html/private:/var/www/private
    image: php-local:local
    restart: no
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: notSecureChangeMe
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: no
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
volumes:
  db:
